mkdir -p app/api/auth/login
mkdir -p app/api/auth/register
mkdir -p app/api/auth/logout
mkdir -p app/api/users
mkdir -p app/api/tools
mkdir -p app/api/locations
mkdir -p app/api/transactions/checkout
mkdir -p app/api/transactions/checkin
mkdir -p app/api/transactions/history
mkdir -p app/dashboard
mkdir -p app/tools
mkdir -p app/locations
mkdir -p app/users
mkdir -p app/login
mkdir -p app/register
mkdir -p components/Dashboard
mkdir -p components/Tools
mkdir -p components/Locations
mkdir -p components/Users
mkdir -p components/Auth
mkdir -p components/Common
mkdir -p lib
mkdir -p utils
mkdir -p context
mkdir -p hooks
mkdir -p styles
mkdir -p prisma
